apiVersion: v1
kind: ConfigMap
metadata:
  name: compliance-checker
  namespace: freightforce
  labels: { app.kubernetes.io/name: compliance-checker, freightforce.io/domain: customs }
data:
  LOG_LEVEL: info
  PORT: "50063"
