apiVersion: velero.io/v1
kind: Schedule
metadata: { name: freightforce-daily, namespace: velero }
spec:
  schedule: "0 2 * * *"
  template:
    includedNamespaces: [freightforce, freightforce-grid-ops, freightforce-ami, freightforce-trading, freightforce-derms]
    snapshotVolumes: true
    ttl: 720h0m0s
