apiVersion: v1
kind: ConfigMap
metadata:
  name: freight-booking
  namespace: freightforce
  labels: { app.kubernetes.io/name: freight-booking, freightforce.io/domain: customs }
data:
  LOG_LEVEL: info
  PORT: "50060"
