apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata: { name: freightforce-default-deny, namespace: freightforce }
spec:
  action: DENY
  rules: [{}]
---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata: { name: allow-from-platform, namespace: freightforce }
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/freightforce/sa/api-gateway
              - cluster.local/ns/freightforce/sa/ops-bff
              - cluster.local/ns/freightforce/sa/customer-bff
              - cluster.local/ns/freightforce/sa/trader-bff
