apiVersion: v1
kind: Service
metadata:
  name: wms-service
  namespace: freightforce
  labels: { app.kubernetes.io/name: wms-service, freightforce.io/domain: warehouse }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50020, targetPort: 50020 }]
  selector: { app.kubernetes.io/name: wms-service }
