config:
  rootDomain: pomerium.freightforce.internal
  generateSignedJWT: true
authenticate:
  idp:
    provider: oidc
    url: https://keycloak.freightforce.internal
ingressController: { enabled: true }
