apiVersion: v1
kind: Service
metadata:
  name: slotting-service
  namespace: freightforce
  labels: { app.kubernetes.io/name: slotting-service, freightforce.io/domain: warehouse }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50021, targetPort: 50021 }]
  selector: { app.kubernetes.io/name: slotting-service }
