apiVersion: v1
kind: ConfigMap
metadata:
  name: refurbishment
  namespace: freightforce
  labels: { app.kubernetes.io/name: refurbishment, freightforce.io/domain: returns }
data:
  LOG_LEVEL: info
  PORT: "50082"
