apiVersion: v1
kind: Service
metadata:
  name: refurbishment
  namespace: freightforce
  labels: { app.kubernetes.io/name: refurbishment, freightforce.io/domain: returns }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50082, targetPort: 50082 }]
  selector: { app.kubernetes.io/name: refurbishment }
