apiVersion: v1
kind: Service
metadata:
  name: carbon-tracker
  namespace: freightforce
  labels: { app.kubernetes.io/name: carbon-tracker, freightforce.io/domain: analytics }
spec:
  type: ClusterIP
  ports: [{ name: http, port: 50143, targetPort: 50143 }]
  selector: { app.kubernetes.io/name: carbon-tracker }
